### ISSUE TITLE
Error following mergersim market.

### ISSUE THREAD

**Issue by OJDC** [bjornerstedt/mergersim#2]
I am trying to implement a single-layer model using ivreg2 for the demand estimation procedure (results withheld) and receive the following error when implementing mergersim market.

`mergersim init, marketsize(average_pop) quantity(passengers) price(averagefare) ///
nests(nest) firm(prodid)
(51 missing values generated)
(51 missing values generated)
--------------------------------------------------------------------------------
MERGERSIM: Merger Simulation Program
Version 1.0, Revision: 218 
--------------------------------------------------------------------------------
Unit demand one-level nested logit

                  Depvar              Price               Group shares
                  --------------------------------------------------------------
                  M_ls                averagefare         M_lsjg
--------------------------------------------------------------------------------
Variables generated: M_ls M_lsjg
--------------------------------------------------------------------------------

. 
. eststo clear

. eststo: ivreg2 M_ls i.prodid  market_distance (averagefare M_lsjg departures_performed = /// 
airline_routes tag average_dest airline_dest_count cheu ),   ///
cluster(marketid)

. 
. mergersim market, keepvars
VariableClass::group_matrix():  3301  subscript invalid [7]
 LogitDemand::get_data():     -  function returned error [25]
  Merger::costestimate():     -  function returned error [9]
                 <istmt>:     -  function returned error
r(3301);

end of do-file'

**Comment by bjornerstedt** [comment]
It is hard to say with so little information. It might have something to do with your nest variable, but that is just a guess. Can you run the model with unnested logit?

**Comment by OJDC** [comment]
Thanks for getting back to me.
When I run without the nest I receive the same error. Is there any other information I can provide that may help solve the issue?

**Comment by bjornerstedt** [comment]
The best way is to have a minimal working example. It might be easier to contact me by mail, and include your script and a minimal dataset.

**Comment by OJDC** [comment]
I have found an issue with my dataset over the weekend and `mergersim` is running as expected now. Apologies for the inconvenience and thank you for your help.
________________________________

**Comment by bjornerstedt** [comment]
What type of issue did you have? Mergersim could check for the inconsistency and respond with a better error message.

**Comment by OJDC** [comment]
I had failed to drop unmatched observations from a 'using' dataset when merging so I had several observations with almost all variables missing. When I dropped these observations the function ran fine.

As a side note, do you have any suggestions for getting the function to converge? I have tried using both Newton and Fixed Point and the Newton method provides useable results, but also warns that it does not converge.


________________________________
